[package]
name = "github-trending-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.15"
soup = "0.5.1"
thiserror = "2.0.12"

[dev-dependencies]
anyhow = "1.0.97"
tokio = { version = "1.44.1", features = ["full"] }
