#[non_exhaustive]
#[derive(Clone, Copy, Debug)]
pub enum Since {
    Daily,
    Weekly,
    Monthly,
}

impl Since {
    pub fn code(self) -> &'static str {
        match self {
            Since::Daily => "daily",
            Since::Weekly => "weekly",
            Since::Monthly => "monthly",
        }
    }
}

#[non_exhaustive]
#[derive(Clone, Copy, Debug)]
pub enum SpokenLanguage {
    Abkhazian,
    Afar,
    Afrikaans,
    Akan,
    Albanian,
    Amharic,
    Arabic,
    Aragonese,
    Armenian,
    Assamese,
    Avaric,
    Avestan,
    Aymara,
    Azerbaijani,
    Bambara,
    Bashkir,
    Basque,
    Belarusian,
    Bengali,
    Bihari,
    Bislama,
    Bosnian,
    Breton,
    Bulgarian,
    Burmese,
    Catalan,
    Chamorro,
    Chechen,
    Chichewa,
    Chinese,
    Chuvash,
    Cornish,
    Corsican,
    Cree,
    Croatian,
    Czech,
    Danish,
    Divehi,
    Dutch,
    Dzongkha,
    English,
    Esperanto,
    Estonian,
    Ewe,
    Faroese,
    Fijian,
    Finnish,
    French,
    Fulah,
    Galician,
    Georgian,
    German,
    Greek,
    Guarani,
    Gujarati,
    Haitian,
    Hausa,
    Hebrew,
    Herero,
    Hindi,
    HiriMotu,
    Hungarian,
    Interlingua,
    Indonesian,
    Interlingue,
    Irish,
    Igbo,
    Inupiaq,
    Ido,
    Icelandic,
    Italian,
    Inuktitut,
    Japanese,
    Javanese,
    Kalaallisut,
    Kannada,
    Kanuri,
    Kashmiri,
    Kazakh,
    CentralKhmer,
    Kikuyu,
    Kinyarwanda,
    Kirghiz,
    Komi,
    Kongo,
    Korean,
    Kurdish,
    Kuanyama,
    Latin,
    Luxembourgish,
    Ganda,
    Limburgan,
    Lingala,
    Lao,
    Lithuanian,
    LubaKatanga,
    Latvian,
    Manx,
    Macedonian,
    Malagasy,
    Malay,
    Malayalam,
    Maltese,
    Maori,
    Marathi,
    Marshallese,
    Mongolian,
    Nauru,
    Navajo,
    NorthNdebele,
    Nepali,
    Ndonga,
    NorwegianBokmål,
    NorwegianNynorsk,
    Norwegian,
    SichuanYi,
    SouthNdebele,
    Occitan,
    Ojibwa,
    ChurchSlavic,
    Oromo,
    Oriya,
    Ossetian,
    Punjabi,
    Pali,
    Persian,
    Polish,
    Pashto,
    Portuguese,
    Quechua,
    Romansh,
    Rundi,
    Romanian,
    Russian,
    Sanskrit,
    Sardinian,
    Sindhi,
    NorthernSami,
    Samoan,
    Sango,
    Serbian,
    Gaelic,
    Shona,
    Sinhala,
    Slovak,
    Slovenian,
    Somali,
    SouthernSotho,
    Spanish,
    Sundanese,
    Swahili,
    Swati,
    Swedish,
    Tamil,
    Telugu,
    Tajik,
    Thai,
    Tigrinya,
    Tibetan,
    Turkmen,
    Tagalog,
    Tswana,
    Tonga,
    Turkish,
    Tsonga,
    Tatar,
    Twi,
    Tahitian,
    Uighur,
    Ukrainian,
    Urdu,
    Uzbek,
    Venda,
    Vietnamese,
    Volapük,
    Walloon,
    Welsh,
    Wolof,
    WesternFrisian,
    Xhosa,
    Yiddish,
    Yoruba,
    Zhuang,
    Zulu,
}

impl SpokenLanguage {
    pub fn code(self) -> &'static str {
        match self {
            SpokenLanguage::Abkhazian => "ab",
            SpokenLanguage::Afar => "aa",
            SpokenLanguage::Afrikaans => "af",
            SpokenLanguage::Akan => "ak",
            SpokenLanguage::Albanian => "sq",
            SpokenLanguage::Amharic => "am",
            SpokenLanguage::Arabic => "ar",
            SpokenLanguage::Aragonese => "an",
            SpokenLanguage::Armenian => "hy",
            SpokenLanguage::Assamese => "as",
            SpokenLanguage::Avaric => "av",
            SpokenLanguage::Avestan => "ae",
            SpokenLanguage::Aymara => "ay",
            SpokenLanguage::Azerbaijani => "az",
            SpokenLanguage::Bambara => "bm",
            SpokenLanguage::Bashkir => "ba",
            SpokenLanguage::Basque => "eu",
            SpokenLanguage::Belarusian => "be",
            SpokenLanguage::Bengali => "bn",
            SpokenLanguage::Bihari => "bh",
            SpokenLanguage::Bislama => "bi",
            SpokenLanguage::Bosnian => "bs",
            SpokenLanguage::Breton => "br",
            SpokenLanguage::Bulgarian => "bg",
            SpokenLanguage::Burmese => "my",
            SpokenLanguage::Catalan => "ca",
            SpokenLanguage::Chamorro => "ch",
            SpokenLanguage::Chechen => "ce",
            SpokenLanguage::Chichewa => "ny",
            SpokenLanguage::Chinese => "zh",
            SpokenLanguage::Chuvash => "cv",
            SpokenLanguage::Cornish => "kw",
            SpokenLanguage::Corsican => "co",
            SpokenLanguage::Cree => "cr",
            SpokenLanguage::Croatian => "hr",
            SpokenLanguage::Czech => "cs",
            SpokenLanguage::Danish => "da",
            SpokenLanguage::Divehi => "dv",
            SpokenLanguage::Dutch => "nl",
            SpokenLanguage::Dzongkha => "dz",
            SpokenLanguage::English => "en",
            SpokenLanguage::Esperanto => "eo",
            SpokenLanguage::Estonian => "et",
            SpokenLanguage::Ewe => "ee",
            SpokenLanguage::Faroese => "fo",
            SpokenLanguage::Fijian => "fj",
            SpokenLanguage::Finnish => "fi",
            SpokenLanguage::French => "fr",
            SpokenLanguage::Fulah => "ff",
            SpokenLanguage::Galician => "gl",
            SpokenLanguage::Georgian => "ka",
            SpokenLanguage::German => "de",
            SpokenLanguage::Greek => "el",
            SpokenLanguage::Guarani => "gn",
            SpokenLanguage::Gujarati => "gu",
            SpokenLanguage::Haitian => "ht",
            SpokenLanguage::Hausa => "ha",
            SpokenLanguage::Hebrew => "he",
            SpokenLanguage::Herero => "hz",
            SpokenLanguage::Hindi => "hi",
            SpokenLanguage::HiriMotu => "ho",
            SpokenLanguage::Hungarian => "hu",
            SpokenLanguage::Interlingua => "ia",
            SpokenLanguage::Indonesian => "id",
            SpokenLanguage::Interlingue => "ie",
            SpokenLanguage::Irish => "ga",
            SpokenLanguage::Igbo => "ig",
            SpokenLanguage::Inupiaq => "ik",
            SpokenLanguage::Ido => "io",
            SpokenLanguage::Icelandic => "is",
            SpokenLanguage::Italian => "it",
            SpokenLanguage::Inuktitut => "iu",
            SpokenLanguage::Japanese => "ja",
            SpokenLanguage::Javanese => "jv",
            SpokenLanguage::Kalaallisut => "kl",
            SpokenLanguage::Kannada => "kn",
            SpokenLanguage::Kanuri => "kr",
            SpokenLanguage::Kashmiri => "ks",
            SpokenLanguage::Kazakh => "kk",
            SpokenLanguage::CentralKhmer => "km",
            SpokenLanguage::Kikuyu => "ki",
            SpokenLanguage::Kinyarwanda => "rw",
            SpokenLanguage::Kirghiz => "ky",
            SpokenLanguage::Komi => "kv",
            SpokenLanguage::Kongo => "kg",
            SpokenLanguage::Korean => "ko",
            SpokenLanguage::Kurdish => "ku",
            SpokenLanguage::Kuanyama => "kj",
            SpokenLanguage::Latin => "la",
            SpokenLanguage::Luxembourgish => "lb",
            SpokenLanguage::Ganda => "lg",
            SpokenLanguage::Limburgan => "li",
            SpokenLanguage::Lingala => "ln",
            SpokenLanguage::Lao => "lo",
            SpokenLanguage::Lithuanian => "lt",
            SpokenLanguage::LubaKatanga => "lu",
            SpokenLanguage::Latvian => "lv",
            SpokenLanguage::Manx => "gv",
            SpokenLanguage::Macedonian => "mk",
            SpokenLanguage::Malagasy => "mg",
            SpokenLanguage::Malay => "ms",
            SpokenLanguage::Malayalam => "ml",
            SpokenLanguage::Maltese => "mt",
            SpokenLanguage::Maori => "mi",
            SpokenLanguage::Marathi => "mr",
            SpokenLanguage::Marshallese => "mh",
            SpokenLanguage::Mongolian => "mn",
            SpokenLanguage::Nauru => "na",
            SpokenLanguage::Navajo => "nv",
            SpokenLanguage::NorthNdebele => "nd",
            SpokenLanguage::Nepali => "ne",
            SpokenLanguage::Ndonga => "ng",
            SpokenLanguage::NorwegianBokmål => "nb",
            SpokenLanguage::NorwegianNynorsk => "nn",
            SpokenLanguage::Norwegian => "no",
            SpokenLanguage::SichuanYi => "ii",
            SpokenLanguage::SouthNdebele => "nr",
            SpokenLanguage::Occitan => "oc",
            SpokenLanguage::Ojibwa => "oj",
            SpokenLanguage::ChurchSlavic => "cu",
            SpokenLanguage::Oromo => "om",
            SpokenLanguage::Oriya => "or",
            SpokenLanguage::Ossetian => "os",
            SpokenLanguage::Punjabi => "pa",
            SpokenLanguage::Pali => "pi",
            SpokenLanguage::Persian => "fa",
            SpokenLanguage::Polish => "pl",
            SpokenLanguage::Pashto => "ps",
            SpokenLanguage::Portuguese => "pt",
            SpokenLanguage::Quechua => "qu",
            SpokenLanguage::Romansh => "rm",
            SpokenLanguage::Rundi => "rn",
            SpokenLanguage::Romanian => "ro",
            SpokenLanguage::Russian => "ru",
            SpokenLanguage::Sanskrit => "sa",
            SpokenLanguage::Sardinian => "sc",
            SpokenLanguage::Sindhi => "sd",
            SpokenLanguage::NorthernSami => "se",
            SpokenLanguage::Samoan => "sm",
            SpokenLanguage::Sango => "sg",
            SpokenLanguage::Serbian => "sr",
            SpokenLanguage::Gaelic => "gd",
            SpokenLanguage::Shona => "sn",
            SpokenLanguage::Sinhala => "si",
            SpokenLanguage::Slovak => "sk",
            SpokenLanguage::Slovenian => "sl",
            SpokenLanguage::Somali => "so",
            SpokenLanguage::SouthernSotho => "st",
            SpokenLanguage::Spanish => "es",
            SpokenLanguage::Sundanese => "su",
            SpokenLanguage::Swahili => "sw",
            SpokenLanguage::Swati => "ss",
            SpokenLanguage::Swedish => "sv",
            SpokenLanguage::Tamil => "ta",
            SpokenLanguage::Telugu => "te",
            SpokenLanguage::Tajik => "tg",
            SpokenLanguage::Thai => "th",
            SpokenLanguage::Tigrinya => "ti",
            SpokenLanguage::Tibetan => "bo",
            SpokenLanguage::Turkmen => "tk",
            SpokenLanguage::Tagalog => "tl",
            SpokenLanguage::Tswana => "tn",
            SpokenLanguage::Tonga => "to",
            SpokenLanguage::Turkish => "tr",
            SpokenLanguage::Tsonga => "ts",
            SpokenLanguage::Tatar => "tt",
            SpokenLanguage::Twi => "tw",
            SpokenLanguage::Tahitian => "ty",
            SpokenLanguage::Uighur => "ug",
            SpokenLanguage::Ukrainian => "uk",
            SpokenLanguage::Urdu => "ur",
            SpokenLanguage::Uzbek => "uz",
            SpokenLanguage::Venda => "ve",
            SpokenLanguage::Vietnamese => "vi",
            SpokenLanguage::Volapük => "vo",
            SpokenLanguage::Walloon => "wa",
            SpokenLanguage::Welsh => "cy",
            SpokenLanguage::Wolof => "wo",
            SpokenLanguage::WesternFrisian => "fy",
            SpokenLanguage::Xhosa => "xh",
            SpokenLanguage::Yiddish => "yi",
            SpokenLanguage::Yoruba => "yo",
            SpokenLanguage::Zhuang => "za",
            SpokenLanguage::Zulu => "zu",
        }
    }
}

#[non_exhaustive]
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug)]
pub enum Language {
    Unknownlanguages,
    _1CEnterprise,
    _2DimensionalArray,
    _4D,
    ABAP,
    ABAPCDS,
    ABNF,
    ActionScript,
    Ada,
    AdblockFilterList,
    AdobeFontMetrics,
    Agda,
    AGSScript,
    AIDL,
    AL,
    Alloy,
    AlpineAbuild,
    AltiumDesigner,
    AMPL,
    AngelScript,
    AnswerSetProgramming,
    AntBuildSystem,
    Antlers,
    ANTLR,
    ApacheConf,
    Apex,
    APIBlueprint,
    APL,
    ApolloGuidanceComputer,
    AppleScript,
    Arc,
    AsciiDoc,
    ASL,
    ASN1,
    ASPNET,
    AspectJ,
    Assembly,
    Astro,
    Asymptote,
    ATS,
    Augeas,
    AutoHotkey,
    AutoIt,
    AvroIDL,
    Awk,
    B4X,
    Ballerina,
    BASIC,
    Batchfile,
    Beef,
    Befunge,
    Berry,
    BibTeX,
    BibTeXStyle,
    Bicep,
    Bikeshed,
    Bison,
    BitBake,
    Blade,
    BlitzBasic,
    BlitzMax,
    Bluespec,
    BluespecBH,
    Boo,
    Boogie,
    BQN,
    Brainfuck,
    BrighterScript,
    Brightscript,
    Browserslist,
    C,
    CSharp,
    CPlusPlus,
    CObjDump,
    C2hsHaskell,
    CabalConfig,
    Caddyfile,
    Cadence,
    Cairo,
    CairoZero,
    CameLIGO,
    CAPCDS,
    CapnProto,
    Carbon,
    CartoCSS,
    Ceylon,
    Chapel,
    Charity,
    Checksums,
    ChucK,
    CIL,
    Circom,
    Cirru,
    Clarion,
    Clarity,
    ClassicASP,
    Clean,
    Click,
    CLIPS,
    Clojure,
    ClosureTemplates,
    CloudFirestoreSecurityRules,
    CMake,
    COBOL,
    CODEOWNERS,
    CodeQL,
    CoffeeScript,
    ColdFusion,
    ColdFusionCFC,
    COLLADA,
    CommonLisp,
    CommonWorkflowLanguage,
    ComponentPascal,
    CoNLLU,
    Cool,
    Coq,
    CppObjDump,
    Creole,
    crontab,
    Crystal,
    CSON,
    Csound,
    CsoundDocument,
    CsoundScore,
    CSS,
    CSV,
    Cuda,
    CUE,
    CueSheet,
    cURLConfig,
    Curry,
    CWeb,
    Cycript,
    Cylc,
    Cypher,
    Cython,
    D,
    DObjDump,
    D2,
    Dafny,
    DarcsPatch,
    Dart,
    DataWeave,
    DebianPackageControlFile,
    DenizenScript,
    desktop,
    Dhall,
    Diff,
    DIGITALCommandLanguage,
    dircolors,
    DirectX3DFile,
    DM,
    DNSZone,
    Dockerfile,
    Dogescript,
    Dotenv,
    DTrace,
    Dune,
    Dylan,
    E,
    Eagle,
    Earthly,
    Easybuild,
    EBNF,
    eC,
    EcereProjects,
    ECL,
    ECLiPSe,
    Ecmarkup,
    Edge,
    EdgeQL,
    EditorConfig,
    EdjeDataCollection,
    edn,
    Eiffel,
    EJS,
    Elixir,
    Elm,
    Elvish,
    ElvishTranscript,
    EmacsLisp,
    EmberScript,
    Email,
    EQ,
    Erlang,
    Euphoria,
    FSharp,
    FStar,
    Factor,
    Fancy,
    Fantom,
    Faust,
    Fennel,
    FIGletFont,
    FilebenchWML,
    Filterscript,
    FIRRTL,
    fish,
    Fluent,
    FLUX,
    Formatted,
    Forth,
    Fortran,
    FortranFreeForm,
    FreeBASIC,
    FreeMarker,
    Frege,
    Futhark,
    Gcode,
    GameMakerLanguage,
    GAML,
    GAMS,
    GAP,
    GCCMachineDescription,
    GDB,
    GDScript,
    GEDCOM,
    GemfileLock,
    Gemini,
    Genero4gl,
    Generoper,
    Genie,
    Genshi,
    GentooEbuild,
    GentooEclass,
    GerberImage,
    GettextCatalog,
    Gherkin,
    GitAttributes,
    GitConfig,
    GitRevisionList,
    Gleam,
    GlimmerJS,
    GlimmerTS,
    GLSL,
    Glyph,
    GlyphBitmapDistributionFormat,
    GN,
    Gnuplot,
    Go,
    GoChecksums,
    GoModule,
    GoWorkspace,
    GodotResource,
    Golo,
    Gosu,
    Grace,
    Gradle,
    GradleKotlinDSL,
    GrammaticalFramework,
    GraphModelingLanguage,
    GraphQL,
    Graphviz,
    Groovy,
    GroovyServerPages,
    GSC,
    Hack,
    Haml,
    Handlebars,
    HAProxy,
    Harbour,
    Hare,
    Haskell,
    Haxe,
    HCL,
    HiveQL,
    HLSL,
    HOCON,
    HolyC,
    hoon,
    HostsFile,
    HTML,
    HTMLPlusECR,
    HTMLPlusEEX,
    HTMLPlusERB,
    HTMLPlusPHP,
    HTMLPlusRazor,
    HTTP,
    HXML,
    Hy,
    HyPhy,
    iCalendar,
    IDL,
    Idris,
    IgnoreList,
    IGORPro,
    ImageJMacro,
    Imba,
    Inform7,
    INI,
    Ink,
    InnoSetup,
    Io,
    Ioke,
    IRClog,
    Isabelle,
    IsabelleROOT,
    ISPC,
    J,
    Jai,
    Janet,
    JARManifest,
    Jasmin,
    Java,
    JavaProperties,
    JavaServerPages,
    JavaTemplateEngine,
    JavaScript,
    JavaScriptPlusERB,
    JCL,
    JestSnapshot,
    JetBrainsMPS,
    JFlex,
    Jinja,
    Jison,
    JisonLex,
    Jolie,
    jq,
    JSON,
    JSONwithComments,
    JSON5,
    JSONiq,
    JSONLD,
    Jsonnet,
    Julia,
    JuliaREPL,
    JupyterNotebook,
    Just,
    KaitaiStruct,
    KakouneScript,
    KDL,
    KerboScript,
    KiCadLayout,
    KiCadLegacyLayout,
    KiCadSchematic,
    Kickstart,
    Kit,
    Kotlin,
    KRL,
    Kusto,
    kvlang,
    LabVIEW,
    Lark,
    Lasso,
    Latte,
    Lean,
    Lean4,
    Less,
    Lex,
    LFE,
    LigoLANG,
    LilyPond,
    Limbo,
    LinearProgramming,
    LinkerScript,
    LinuxKernelModule,
    Liquid,
    LiterateAgda,
    LiterateCoffeeScript,
    LiterateHaskell,
    LiveCodeScript,
    LiveScript,
    LLVM,
    Logos,
    Logtalk,
    LOLCODE,
    LookML,
    LoomScript,
    LSL,
    LTspiceSymbol,
    Lua,
    Luau,
    M,
    M4,
    M4Sugar,
    Macaulay2,
    Makefile,
    Mako,
    Markdown,
    Marko,
    Mask,
    Mathematica,
    MATLAB,
    MavenPOM,
    Max,
    MAXScript,
    mcfunction,
    mdsvex,
    MDX,
    Mercury,
    Mermaid,
    Meson,
    Metal,
    MicrosoftDeveloperStudioProject,
    MicrosoftVisualStudioSolution,
    MiniD,
    MiniYAML,
    MiniZinc,
    MiniZincData,
    Mint,
    Mirah,
    mIRCScript,
    MLIR,
    Modelica,
    Modula2,
    Modula3,
    ModuleManagementSystem,
    Mojo,
    Monkey,
    MonkeyC,
    Moocode,
    MoonBit,
    MoonScript,
    Motoko,
    Motorola68KAssembly,
    Move,
    MQL4,
    MQL5,
    MTML,
    MUF,
    mupad,
    Muse,
    Mustache,
    Myghty,
    nanorc,
    Nasal,
    NASL,
    NCL,
    Nearley,
    Nemerle,
    NEON,
    nesC,
    NetLinx,
    NetLinxPlusERB,
    NetLogo,
    NewLisp,
    Nextflow,
    Nginx,
    Nim,
    Ninja,
    Nit,
    Nix,
    NL,
    NMODL,
    Noir,
    NPMConfig,
    NSIS,
    Nu,
    NumPy,
    Nunjucks,
    Nushell,
    NWScript,
    OASv2json,
    OASv2yaml,
    OASv3json,
    OASv3yaml,
    Oberon,
    ObjDump,
    ObjectDataInstanceNotation,
    ObjectiveC,
    ObjectiveCPlusPlus,
    ObjectiveJ,
    ObjectScript,
    OCaml,
    Odin,
    Omgrofl,
    OMNeTPlusPlusMSG,
    OMNeTPlusPlusNED,
    ooc,
    Opa,
    Opal,
    OpenPolicyAgent,
    OpenAPISpecificationv2,
    OpenAPISpecificationv3,
    OpenCL,
    OpenEdgeABL,
    OpenQASM,
    OpenRCrunscript,
    OpenSCAD,
    OpenStepPropertyList,
    OpenTypeFeatureFile,
    OptionList,
    Org,
    OverpassQL,
    Ox,
    Oxygene,
    Oz,
    P4,
    Pact,
    Pan,
    Papyrus,
    Parrot,
    ParrotAssembly,
    ParrotInternalRepresentation,
    Pascal,
    Pawn,
    PDDL,
    PEGjs,
    Pep8,
    Perl,
    PHP,
    Pic,
    Pickle,
    PicoLisp,
    PigLatin,
    Pike,
    PipRequirements,
    Pkl,
    PlantUML,
    PLpgSQL,
    PLSQL,
    Pod,
    Pod6,
    PogoScript,
    Polar,
    Pony,
    Portugol,
    PostCSS,
    PostScript,
    POVRaySDL,
    PowerBuilder,
    PowerShell,
    Praat,
    Prisma,
    Processing,
    Procfile,
    Proguard,
    Prolog,
    Promela,
    PropellerSpin,
    ProtocolBuffer,
    ProtocolBufferTextFormat,
    PublicKey,
    Pug,
    Puppet,
    PureData,
    PureBasic,
    PureScript,
    Pyret,
    Python,
    Pythonconsole,
    Pythontraceback,
    q,
    QSharp,
    QMake,
    QML,
    QtScript,
    Quake,
    QuickBASIC,
    R,
    Racket,
    Ragel,
    Raku,
    RAML,
    Rascal,
    Rawtokendata,
    RBS,
    RDoc,
    ReadlineConfig,
    REALbasic,
    Reason,
    ReasonLIGO,
    Rebol,
    RecordJar,
    Red,
    Redcode,
    RedirectRules,
    RegularExpression,
    RenPy,
    RenderScript,
    ReScript,
    reStructuredText,
    REXX,
    Rez,
    RichTextFormat,
    Ring,
    Riot,
    RMarkdown,
    RobotFramework,
    robotstxt,
    Roc,
    Roff,
    RoffManpage,
    RON,
    Rouge,
    RouterOSScript,
    RPC,
    RPGLE,
    RPMSpec,
    Ruby,
    RUNOFF,
    Rust,
    Sage,
    SaltStack,
    SAS,
    Sass,
    Scala,
    Scaml,
    Scenic,
    Scheme,
    Scilab,
    SCSS,
    sed,
    _Self,
    SELinuxPolicy,
    ShaderLab,
    Shell,
    ShellCheckConfig,
    ShellSession,
    Shen,
    Sieve,
    SimpleFileVerification,
    Singularity,
    Slang,
    Slash,
    Slice,
    Slim,
    Slint,
    Smali,
    Smalltalk,
    Smarty,
    Smithy,
    SmPL,
    SMT,
    Snakemake,
    Solidity,
    Soong,
    SourcePawn,
    SPARQL,
    SplineFontDatabase,
    SQF,
    SQL,
    SQLPL,
    Squirrel,
    SRecodeTemplate,
    SSHConfig,
    Stan,
    StandardML,
    STAR,
    Starlark,
    Stata,
    STL,
    STON,
    StringTemplate,
    Stylus,
    SubRipText,
    SugarSS,
    SuperCollider,
    Svelte,
    SVG,
    Sway,
    Sweave,
    Swift,
    SWIG,
    SystemVerilog,
    Tact,
    Talon,
    Tcl,
    Tcsh,
    Tea,
    templ,
    Terra,
    TerraformTemplate,
    TeX,
    Texinfo,
    Text,
    TextGrid,
    Textile,
    TextMateProperties,
    Thrift,
    TIProgram,
    TLVerilog,
    TLA,
    Toit,
    TOML,
    TreesitterQuery,
    TSPLIBdata,
    TSQL,
    TSV,
    TSX,
    Turing,
    Turtle,
    Twig,
    TXL,
    TypeLanguage,
    TypeScript,
    TypeSpec,
    Typst,
    UnifiedParallelC,
    Unity3DAsset,
    UnixAssembly,
    Uno,
    UnrealScript,
    UrWeb,
    V,
    Vala,
    ValveDataFormat,
    VBA,
    VBScript,
    vCard,
    VCL,
    VelocityTemplateLanguage,
    Verilog,
    VHDL,
    VimHelpFile,
    VimScript,
    VimSnippet,
    VisualBasicNET,
    VisualBasic6_0,
    Volt,
    Vue,
    Vyper,
    WavefrontMaterial,
    WavefrontObject,
    WDL,
    WebOntologyLanguage,
    WebAssembly,
    WebAssemblyInterfaceType,
    WebIDL,
    WebVTT,
    WgetConfig,
    WGSL,
    Whiley,
    Wikitext,
    Win32MessageFile,
    WindowsRegistryEntries,
    wisp,
    WitcherScript,
    Wollok,
    WorldofWarcraftAddonData,
    Wren,
    XBitMap,
    XFontDirectoryIndex,
    XPixMap,
    X10,
    xBase,
    XC,
    XCompose,
    Xmake,
    XML,
    XMLPropertyList,
    Xojo,
    Xonsh,
    XPages,
    XProc,
    XQuery,
    XS,
    XSLT,
    Xtend,
    Yacc,
    YAML,
    YANG,
    YARA,
    YASnippet,
    Yul,
    ZAP,
    Zeek,
    ZenScript,
    Zephir,
    Zig,
    ZIL,
    Zimpl,
}

impl Language {
    pub fn code(self) -> &'static str {
        match self {
            Language::Unknownlanguages => "unknown",
            Language::_1CEnterprise => "1c-enterprise",
            Language::_2DimensionalArray => "2-dimensional-array",
            Language::_4D => "4d",
            Language::ABAP => "abap",
            Language::ABAPCDS => "abap-cds",
            Language::ABNF => "abnf",
            Language::ActionScript => "actionscript",
            Language::Ada => "ada",
            Language::AdblockFilterList => "adblock-filter-list",
            Language::AdobeFontMetrics => "adobe-font-metrics",
            Language::Agda => "agda",
            Language::AGSScript => "ags-script",
            Language::AIDL => "aidl",
            Language::AL => "al",
            Language::Alloy => "alloy",
            Language::AlpineAbuild => "alpine-abuild",
            Language::AltiumDesigner => "altium-designer",
            Language::AMPL => "ampl",
            Language::AngelScript => "angelscript",
            Language::AnswerSetProgramming => "answer-set-programming",
            Language::AntBuildSystem => "ant-build-system",
            Language::Antlers => "antlers",
            Language::ANTLR => "antlr",
            Language::ApacheConf => "apacheconf",
            Language::Apex => "apex",
            Language::APIBlueprint => "api-blueprint",
            Language::APL => "apl",
            Language::ApolloGuidanceComputer => "apollo-guidance-computer",
            Language::AppleScript => "applescript",
            Language::Arc => "arc",
            Language::AsciiDoc => "asciidoc",
            Language::ASL => "asl",
            Language::ASN1 => "asn.1",
            Language::ASPNET => "asp.net",
            Language::AspectJ => "aspectj",
            Language::Assembly => "assembly",
            Language::Astro => "astro",
            Language::Asymptote => "asymptote",
            Language::ATS => "ats",
            Language::Augeas => "augeas",
            Language::AutoHotkey => "autohotkey",
            Language::AutoIt => "autoit",
            Language::AvroIDL => "avro-idl",
            Language::Awk => "awk",
            Language::B4X => "b4x",
            Language::Ballerina => "ballerina",
            Language::BASIC => "basic",
            Language::Batchfile => "batchfile",
            Language::Beef => "beef",
            Language::Befunge => "befunge",
            Language::Berry => "berry",
            Language::BibTeX => "bibtex",
            Language::BibTeXStyle => "bibtex-style",
            Language::Bicep => "bicep",
            Language::Bikeshed => "bikeshed",
            Language::Bison => "bison",
            Language::BitBake => "bitbake",
            Language::Blade => "blade",
            Language::BlitzBasic => "blitzbasic",
            Language::BlitzMax => "blitzmax",
            Language::Bluespec => "bluespec",
            Language::BluespecBH => "bluespec-bh",
            Language::Boo => "boo",
            Language::Boogie => "boogie",
            Language::BQN => "bqn",
            Language::Brainfuck => "brainfuck",
            Language::BrighterScript => "brighterscript",
            Language::Brightscript => "brightscript",
            Language::Browserslist => "browserslist",
            Language::C => "c",
            Language::CSharp => "c%23",
            Language::CPlusPlus => "c++",
            Language::CObjDump => "c-objdump",
            Language::C2hsHaskell => "c2hs-haskell",
            Language::CabalConfig => "cabal-config",
            Language::Caddyfile => "caddyfile",
            Language::Cadence => "cadence",
            Language::Cairo => "cairo",
            Language::CairoZero => "cairo-zero",
            Language::CameLIGO => "cameligo",
            Language::CAPCDS => "cap-cds",
            Language::CapnProto => "cap'n-proto",
            Language::Carbon => "carbon",
            Language::CartoCSS => "cartocss",
            Language::Ceylon => "ceylon",
            Language::Chapel => "chapel",
            Language::Charity => "charity",
            Language::Checksums => "checksums",
            Language::ChucK => "chuck",
            Language::CIL => "cil",
            Language::Circom => "circom",
            Language::Cirru => "cirru",
            Language::Clarion => "clarion",
            Language::Clarity => "clarity",
            Language::ClassicASP => "classic-asp",
            Language::Clean => "clean",
            Language::Click => "click",
            Language::CLIPS => "clips",
            Language::Clojure => "clojure",
            Language::ClosureTemplates => "closure-templates",
            Language::CloudFirestoreSecurityRules => "cloud-firestore-security-rules",
            Language::CMake => "cmake",
            Language::COBOL => "cobol",
            Language::CODEOWNERS => "codeowners",
            Language::CodeQL => "codeql",
            Language::CoffeeScript => "coffeescript",
            Language::ColdFusion => "coldfusion",
            Language::ColdFusionCFC => "coldfusion-cfc",
            Language::COLLADA => "collada",
            Language::CommonLisp => "common-lisp",
            Language::CommonWorkflowLanguage => "common-workflow-language",
            Language::ComponentPascal => "component-pascal",
            Language::CoNLLU => "conll-u",
            Language::Cool => "cool",
            Language::Coq => "coq",
            Language::CppObjDump => "cpp-objdump",
            Language::Creole => "creole",
            Language::crontab => "crontab",
            Language::Crystal => "crystal",
            Language::CSON => "cson",
            Language::Csound => "csound",
            Language::CsoundDocument => "csound-document",
            Language::CsoundScore => "csound-score",
            Language::CSS => "css",
            Language::CSV => "csv",
            Language::Cuda => "cuda",
            Language::CUE => "cue",
            Language::CueSheet => "cue-sheet",
            Language::cURLConfig => "curl-config",
            Language::Curry => "curry",
            Language::CWeb => "cweb",
            Language::Cycript => "cycript",
            Language::Cylc => "cylc",
            Language::Cypher => "cypher",
            Language::Cython => "cython",
            Language::D => "d",
            Language::DObjDump => "d-objdump",
            Language::D2 => "d2",
            Language::Dafny => "dafny",
            Language::DarcsPatch => "darcs-patch",
            Language::Dart => "dart",
            Language::DataWeave => "dataweave",
            Language::DebianPackageControlFile => "debian-package-control-file",
            Language::DenizenScript => "denizenscript",
            Language::desktop => "desktop",
            Language::Dhall => "dhall",
            Language::Diff => "diff",
            Language::DIGITALCommandLanguage => "digital-command-language",
            Language::dircolors => "dircolors",
            Language::DirectX3DFile => "directx-3d-file",
            Language::DM => "dm",
            Language::DNSZone => "dns-zone",
            Language::Dockerfile => "dockerfile",
            Language::Dogescript => "dogescript",
            Language::Dotenv => "dotenv",
            Language::DTrace => "dtrace",
            Language::Dune => "dune",
            Language::Dylan => "dylan",
            Language::E => "e",
            Language::Eagle => "eagle",
            Language::Earthly => "earthly",
            Language::Easybuild => "easybuild",
            Language::EBNF => "ebnf",
            Language::eC => "ec",
            Language::EcereProjects => "ecere-projects",
            Language::ECL => "ecl",
            Language::ECLiPSe => "eclipse",
            Language::Ecmarkup => "ecmarkup",
            Language::Edge => "edge",
            Language::EdgeQL => "edgeql",
            Language::EditorConfig => "editorconfig",
            Language::EdjeDataCollection => "edje-data-collection",
            Language::edn => "edn",
            Language::Eiffel => "eiffel",
            Language::EJS => "ejs",
            Language::Elixir => "elixir",
            Language::Elm => "elm",
            Language::Elvish => "elvish",
            Language::ElvishTranscript => "elvish-transcript",
            Language::EmacsLisp => "emacs-lisp",
            Language::EmberScript => "emberscript",
            Language::Email => "e-mail",
            Language::EQ => "eq",
            Language::Erlang => "erlang",
            Language::Euphoria => "euphoria",
            Language::FSharp => "f%23",
            Language::FStar => "f*",
            Language::Factor => "factor",
            Language::Fancy => "fancy",
            Language::Fantom => "fantom",
            Language::Faust => "faust",
            Language::Fennel => "fennel",
            Language::FIGletFont => "figlet-font",
            Language::FilebenchWML => "filebench-wml",
            Language::Filterscript => "filterscript",
            Language::FIRRTL => "firrtl",
            Language::fish => "fish",
            Language::Fluent => "fluent",
            Language::FLUX => "flux",
            Language::Formatted => "formatted",
            Language::Forth => "forth",
            Language::Fortran => "fortran",
            Language::FortranFreeForm => "fortran-free-form",
            Language::FreeBASIC => "freebasic",
            Language::FreeMarker => "freemarker",
            Language::Frege => "frege",
            Language::Futhark => "futhark",
            Language::Gcode => "g-code",
            Language::GameMakerLanguage => "game-maker-language",
            Language::GAML => "gaml",
            Language::GAMS => "gams",
            Language::GAP => "gap",
            Language::GCCMachineDescription => "gcc-machine-description",
            Language::GDB => "gdb",
            Language::GDScript => "gdscript",
            Language::GEDCOM => "gedcom",
            Language::GemfileLock => "gemfile.lock",
            Language::Gemini => "gemini",
            Language::Genero4gl => "genero-4gl",
            Language::Generoper => "genero-per",
            Language::Genie => "genie",
            Language::Genshi => "genshi",
            Language::GentooEbuild => "gentoo-ebuild",
            Language::GentooEclass => "gentoo-eclass",
            Language::GerberImage => "gerber-image",
            Language::GettextCatalog => "gettext-catalog",
            Language::Gherkin => "gherkin",
            Language::GitAttributes => "git-attributes",
            Language::GitConfig => "git-config",
            Language::GitRevisionList => "git-revision-list",
            Language::Gleam => "gleam",
            Language::GlimmerJS => "glimmer-js",
            Language::GlimmerTS => "glimmer-ts",
            Language::GLSL => "glsl",
            Language::Glyph => "glyph",
            Language::GlyphBitmapDistributionFormat => "glyph-bitmap-distribution-format",
            Language::GN => "gn",
            Language::Gnuplot => "gnuplot",
            Language::Go => "go",
            Language::GoChecksums => "go-checksums",
            Language::GoModule => "go-module",
            Language::GoWorkspace => "go-workspace",
            Language::GodotResource => "godot-resource",
            Language::Golo => "golo",
            Language::Gosu => "gosu",
            Language::Grace => "grace",
            Language::Gradle => "gradle",
            Language::GradleKotlinDSL => "gradle-kotlin-dsl",
            Language::GrammaticalFramework => "grammatical-framework",
            Language::GraphModelingLanguage => "graph-modeling-language",
            Language::GraphQL => "graphql",
            Language::Graphviz => "graphviz-(dot)",
            Language::Groovy => "groovy",
            Language::GroovyServerPages => "groovy-server-pages",
            Language::GSC => "gsc",
            Language::Hack => "hack",
            Language::Haml => "haml",
            Language::Handlebars => "handlebars",
            Language::HAProxy => "haproxy",
            Language::Harbour => "harbour",
            Language::Hare => "hare",
            Language::Haskell => "haskell",
            Language::Haxe => "haxe",
            Language::HCL => "hcl",
            Language::HiveQL => "hiveql",
            Language::HLSL => "hlsl",
            Language::HOCON => "hocon",
            Language::HolyC => "holyc",
            Language::hoon => "hoon",
            Language::HostsFile => "hosts-file",
            Language::HTML => "html",
            Language::HTMLPlusECR => "html+ecr",
            Language::HTMLPlusEEX => "html+eex",
            Language::HTMLPlusERB => "html+erb",
            Language::HTMLPlusPHP => "html+php",
            Language::HTMLPlusRazor => "html+razor",
            Language::HTTP => "http",
            Language::HXML => "hxml",
            Language::Hy => "hy",
            Language::HyPhy => "hyphy",
            Language::iCalendar => "icalendar",
            Language::IDL => "idl",
            Language::Idris => "idris",
            Language::IgnoreList => "ignore-list",
            Language::IGORPro => "igor-pro",
            Language::ImageJMacro => "imagej-macro",
            Language::Imba => "imba",
            Language::Inform7 => "inform-7",
            Language::INI => "ini",
            Language::Ink => "ink",
            Language::InnoSetup => "inno-setup",
            Language::Io => "io",
            Language::Ioke => "ioke",
            Language::IRClog => "irc-log",
            Language::Isabelle => "isabelle",
            Language::IsabelleROOT => "isabelle-root",
            Language::ISPC => "ispc",
            Language::J => "j",
            Language::Jai => "jai",
            Language::Janet => "janet",
            Language::JARManifest => "jar-manifest",
            Language::Jasmin => "jasmin",
            Language::Java => "java",
            Language::JavaProperties => "java-properties",
            Language::JavaServerPages => "java-server-pages",
            Language::JavaTemplateEngine => "java-template-engine",
            Language::JavaScript => "javascript",
            Language::JavaScriptPlusERB => "javascript+erb",
            Language::JCL => "jcl",
            Language::JestSnapshot => "jest-snapshot",
            Language::JetBrainsMPS => "jetbrains-mps",
            Language::JFlex => "jflex",
            Language::Jinja => "jinja",
            Language::Jison => "jison",
            Language::JisonLex => "jison-lex",
            Language::Jolie => "jolie",
            Language::jq => "jq",
            Language::JSON => "json",
            Language::JSONwithComments => "json-with-comments",
            Language::JSON5 => "json5",
            Language::JSONiq => "jsoniq",
            Language::JSONLD => "jsonld",
            Language::Jsonnet => "jsonnet",
            Language::Julia => "julia",
            Language::JuliaREPL => "julia-repl",
            Language::JupyterNotebook => "jupyter-notebook",
            Language::Just => "just",
            Language::KaitaiStruct => "kaitai-struct",
            Language::KakouneScript => "kakounescript",
            Language::KDL => "kdl",
            Language::KerboScript => "kerboscript",
            Language::KiCadLayout => "kicad-layout",
            Language::KiCadLegacyLayout => "kicad-legacy-layout",
            Language::KiCadSchematic => "kicad-schematic",
            Language::Kickstart => "kickstart",
            Language::Kit => "kit",
            Language::Kotlin => "kotlin",
            Language::KRL => "krl",
            Language::Kusto => "kusto",
            Language::kvlang => "kvlang",
            Language::LabVIEW => "labview",
            Language::Lark => "lark",
            Language::Lasso => "lasso",
            Language::Latte => "latte",
            Language::Lean => "lean",
            Language::Lean4 => "lean-4",
            Language::Less => "less",
            Language::Lex => "lex",
            Language::LFE => "lfe",
            Language::LigoLANG => "ligolang",
            Language::LilyPond => "lilypond",
            Language::Limbo => "limbo",
            Language::LinearProgramming => "linear-programming",
            Language::LinkerScript => "linker-script",
            Language::LinuxKernelModule => "linux-kernel-module",
            Language::Liquid => "liquid",
            Language::LiterateAgda => "literate-agda",
            Language::LiterateCoffeeScript => "literate-coffeescript",
            Language::LiterateHaskell => "literate-haskell",
            Language::LiveCodeScript => "livecode-script",
            Language::LiveScript => "livescript",
            Language::LLVM => "llvm",
            Language::Logos => "logos",
            Language::Logtalk => "logtalk",
            Language::LOLCODE => "lolcode",
            Language::LookML => "lookml",
            Language::LoomScript => "loomscript",
            Language::LSL => "lsl",
            Language::LTspiceSymbol => "ltspice-symbol",
            Language::Lua => "lua",
            Language::Luau => "luau",
            Language::M => "m",
            Language::M4 => "m4",
            Language::M4Sugar => "m4sugar",
            Language::Macaulay2 => "macaulay2",
            Language::Makefile => "makefile",
            Language::Mako => "mako",
            Language::Markdown => "markdown",
            Language::Marko => "marko",
            Language::Mask => "mask",
            Language::Mathematica => "mathematica",
            Language::MATLAB => "matlab",
            Language::MavenPOM => "maven-pom",
            Language::Max => "max",
            Language::MAXScript => "maxscript",
            Language::mcfunction => "mcfunction",
            Language::mdsvex => "mdsvex",
            Language::MDX => "mdx",
            Language::Mercury => "mercury",
            Language::Mermaid => "mermaid",
            Language::Meson => "meson",
            Language::Metal => "metal",
            Language::MicrosoftDeveloperStudioProject => "microsoft-developer-studio-project",
            Language::MicrosoftVisualStudioSolution => "microsoft-visual-studio-solution",
            Language::MiniD => "minid",
            Language::MiniYAML => "miniyaml",
            Language::MiniZinc => "minizinc",
            Language::MiniZincData => "minizinc-data",
            Language::Mint => "mint",
            Language::Mirah => "mirah",
            Language::mIRCScript => "mirc-script",
            Language::MLIR => "mlir",
            Language::Modelica => "modelica",
            Language::Modula2 => "modula-2",
            Language::Modula3 => "modula-3",
            Language::ModuleManagementSystem => "module-management-system",
            Language::Mojo => "mojo",
            Language::Monkey => "monkey",
            Language::MonkeyC => "monkey-c",
            Language::Moocode => "moocode",
            Language::MoonBit => "moonbit",
            Language::MoonScript => "moonscript",
            Language::Motoko => "motoko",
            Language::Motorola68KAssembly => "motorola-68k-assembly",
            Language::Move => "move",
            Language::MQL4 => "mql4",
            Language::MQL5 => "mql5",
            Language::MTML => "mtml",
            Language::MUF => "muf",
            Language::mupad => "mupad",
            Language::Muse => "muse",
            Language::Mustache => "mustache",
            Language::Myghty => "myghty",
            Language::nanorc => "nanorc",
            Language::Nasal => "nasal",
            Language::NASL => "nasl",
            Language::NCL => "ncl",
            Language::Nearley => "nearley",
            Language::Nemerle => "nemerle",
            Language::NEON => "neon",
            Language::nesC => "nesc",
            Language::NetLinx => "netlinx",
            Language::NetLinxPlusERB => "netlinx+erb",
            Language::NetLogo => "netlogo",
            Language::NewLisp => "newlisp",
            Language::Nextflow => "nextflow",
            Language::Nginx => "nginx",
            Language::Nim => "nim",
            Language::Ninja => "ninja",
            Language::Nit => "nit",
            Language::Nix => "nix",
            Language::NL => "nl",
            Language::NMODL => "nmodl",
            Language::Noir => "noir",
            Language::NPMConfig => "npm-config",
            Language::NSIS => "nsis",
            Language::Nu => "nu",
            Language::NumPy => "numpy",
            Language::Nunjucks => "nunjucks",
            Language::Nushell => "nushell",
            Language::NWScript => "nwscript",
            Language::OASv2json => "oasv2-json",
            Language::OASv2yaml => "oasv2-yaml",
            Language::OASv3json => "oasv3-json",
            Language::OASv3yaml => "oasv3-yaml",
            Language::Oberon => "oberon",
            Language::ObjDump => "objdump",
            Language::ObjectDataInstanceNotation => "object-data-instance-notation",
            Language::ObjectiveC => "objective-c",
            Language::ObjectiveCPlusPlus => "objective-c++",
            Language::ObjectiveJ => "objective-j",
            Language::ObjectScript => "objectscript",
            Language::OCaml => "ocaml",
            Language::Odin => "odin",
            Language::Omgrofl => "omgrofl",
            Language::OMNeTPlusPlusMSG => "omnet++-msg",
            Language::OMNeTPlusPlusNED => "omnet++-ned",
            Language::ooc => "ooc",
            Language::Opa => "opa",
            Language::Opal => "opal",
            Language::OpenPolicyAgent => "open-policy-agent",
            Language::OpenAPISpecificationv2 => "openapi-specification-v2",
            Language::OpenAPISpecificationv3 => "openapi-specification-v3",
            Language::OpenCL => "opencl",
            Language::OpenEdgeABL => "openedge-abl",
            Language::OpenQASM => "openqasm",
            Language::OpenRCrunscript => "openrc-runscript",
            Language::OpenSCAD => "openscad",
            Language::OpenStepPropertyList => "openstep-property-list",
            Language::OpenTypeFeatureFile => "opentype-feature-file",
            Language::OptionList => "option-list",
            Language::Org => "org",
            Language::OverpassQL => "overpassql",
            Language::Ox => "ox",
            Language::Oxygene => "oxygene",
            Language::Oz => "oz",
            Language::P4 => "p4",
            Language::Pact => "pact",
            Language::Pan => "pan",
            Language::Papyrus => "papyrus",
            Language::Parrot => "parrot",
            Language::ParrotAssembly => "parrot-assembly",
            Language::ParrotInternalRepresentation => "parrot-internal-representation",
            Language::Pascal => "pascal",
            Language::Pawn => "pawn",
            Language::PDDL => "pddl",
            Language::PEGjs => "peg.js",
            Language::Pep8 => "pep8",
            Language::Perl => "perl",
            Language::PHP => "php",
            Language::Pic => "pic",
            Language::Pickle => "pickle",
            Language::PicoLisp => "picolisp",
            Language::PigLatin => "piglatin",
            Language::Pike => "pike",
            Language::PipRequirements => "pip-requirements",
            Language::Pkl => "pkl",
            Language::PlantUML => "plantuml",
            Language::PLpgSQL => "plpgsql",
            Language::PLSQL => "plsql",
            Language::Pod => "pod",
            Language::Pod6 => "pod-6",
            Language::PogoScript => "pogoscript",
            Language::Polar => "polar",
            Language::Pony => "pony",
            Language::Portugol => "portugol",
            Language::PostCSS => "postcss",
            Language::PostScript => "postscript",
            Language::POVRaySDL => "pov-ray-sdl",
            Language::PowerBuilder => "powerbuilder",
            Language::PowerShell => "powershell",
            Language::Praat => "praat",
            Language::Prisma => "prisma",
            Language::Processing => "processing",
            Language::Procfile => "procfile",
            Language::Proguard => "proguard",
            Language::Prolog => "prolog",
            Language::Promela => "promela",
            Language::PropellerSpin => "propeller-spin",
            Language::ProtocolBuffer => "protocol-buffer",
            Language::ProtocolBufferTextFormat => "protocol-buffer-text-format",
            Language::PublicKey => "public-key",
            Language::Pug => "pug",
            Language::Puppet => "puppet",
            Language::PureData => "pure-data",
            Language::PureBasic => "purebasic",
            Language::PureScript => "purescript",
            Language::Pyret => "pyret",
            Language::Python => "python",
            Language::Pythonconsole => "python-console",
            Language::Pythontraceback => "python-traceback",
            Language::q => "q",
            Language::QSharp => "q%23",
            Language::QMake => "qmake",
            Language::QML => "qml",
            Language::QtScript => "qt-script",
            Language::Quake => "quake",
            Language::QuickBASIC => "quickbasic",
            Language::R => "r",
            Language::Racket => "racket",
            Language::Ragel => "ragel",
            Language::Raku => "raku",
            Language::RAML => "raml",
            Language::Rascal => "rascal",
            Language::Rawtokendata => "raw-token-data",
            Language::RBS => "rbs",
            Language::RDoc => "rdoc",
            Language::ReadlineConfig => "readline-config",
            Language::REALbasic => "realbasic",
            Language::Reason => "reason",
            Language::ReasonLIGO => "reasonligo",
            Language::Rebol => "rebol",
            Language::RecordJar => "record-jar",
            Language::Red => "red",
            Language::Redcode => "redcode",
            Language::RedirectRules => "redirect-rules",
            Language::RegularExpression => "regular-expression",
            Language::RenPy => "ren'py",
            Language::RenderScript => "renderscript",
            Language::ReScript => "rescript",
            Language::reStructuredText => "restructuredtext",
            Language::REXX => "rexx",
            Language::Rez => "rez",
            Language::RichTextFormat => "rich-text-format",
            Language::Ring => "ring",
            Language::Riot => "riot",
            Language::RMarkdown => "rmarkdown",
            Language::RobotFramework => "robotframework",
            Language::robotstxt => "robots.txt",
            Language::Roc => "roc",
            Language::Roff => "roff",
            Language::RoffManpage => "roff-manpage",
            Language::RON => "ron",
            Language::Rouge => "rouge",
            Language::RouterOSScript => "routeros-script",
            Language::RPC => "rpc",
            Language::RPGLE => "rpgle",
            Language::RPMSpec => "rpm-spec",
            Language::Ruby => "ruby",
            Language::RUNOFF => "runoff",
            Language::Rust => "rust",
            Language::Sage => "sage",
            Language::SaltStack => "saltstack",
            Language::SAS => "sas",
            Language::Sass => "sass",
            Language::Scala => "scala",
            Language::Scaml => "scaml",
            Language::Scenic => "scenic",
            Language::Scheme => "scheme",
            Language::Scilab => "scilab",
            Language::SCSS => "scss",
            Language::sed => "sed",
            Language::_Self => "self",
            Language::SELinuxPolicy => "selinux-policy",
            Language::ShaderLab => "shaderlab",
            Language::Shell => "shell",
            Language::ShellCheckConfig => "shellcheck-config",
            Language::ShellSession => "shellsession",
            Language::Shen => "shen",
            Language::Sieve => "sieve",
            Language::SimpleFileVerification => "simple-file-verification",
            Language::Singularity => "singularity",
            Language::Slang => "slang",
            Language::Slash => "slash",
            Language::Slice => "slice",
            Language::Slim => "slim",
            Language::Slint => "slint",
            Language::Smali => "smali",
            Language::Smalltalk => "smalltalk",
            Language::Smarty => "smarty",
            Language::Smithy => "smithy",
            Language::SmPL => "smpl",
            Language::SMT => "smt",
            Language::Snakemake => "snakemake",
            Language::Solidity => "solidity",
            Language::Soong => "soong",
            Language::SourcePawn => "sourcepawn",
            Language::SPARQL => "sparql",
            Language::SplineFontDatabase => "spline-font-database",
            Language::SQF => "sqf",
            Language::SQL => "sql",
            Language::SQLPL => "sqlpl",
            Language::Squirrel => "squirrel",
            Language::SRecodeTemplate => "srecode-template",
            Language::SSHConfig => "ssh-config",
            Language::Stan => "stan",
            Language::StandardML => "standard-ml",
            Language::STAR => "star",
            Language::Starlark => "starlark",
            Language::Stata => "stata",
            Language::STL => "stl",
            Language::STON => "ston",
            Language::StringTemplate => "stringtemplate",
            Language::Stylus => "stylus",
            Language::SubRipText => "subrip-text",
            Language::SugarSS => "sugarss",
            Language::SuperCollider => "supercollider",
            Language::Svelte => "svelte",
            Language::SVG => "svg",
            Language::Sway => "sway",
            Language::Sweave => "sweave",
            Language::Swift => "swift",
            Language::SWIG => "swig",
            Language::SystemVerilog => "systemverilog",
            Language::Tact => "tact",
            Language::Talon => "talon",
            Language::Tcl => "tcl",
            Language::Tcsh => "tcsh",
            Language::Tea => "tea",
            Language::templ => "templ",
            Language::Terra => "terra",
            Language::TerraformTemplate => "terraform-template",
            Language::TeX => "tex",
            Language::Texinfo => "texinfo",
            Language::Text => "text",
            Language::TextGrid => "textgrid",
            Language::Textile => "textile",
            Language::TextMateProperties => "textmate-properties",
            Language::Thrift => "thrift",
            Language::TIProgram => "ti-program",
            Language::TLVerilog => "tl-verilog",
            Language::TLA => "tla",
            Language::Toit => "toit",
            Language::TOML => "toml",
            Language::TreesitterQuery => "tree-sitter-query",
            Language::TSPLIBdata => "tsplib-data",
            Language::TSQL => "tsql",
            Language::TSV => "tsv",
            Language::TSX => "tsx",
            Language::Turing => "turing",
            Language::Turtle => "turtle",
            Language::Twig => "twig",
            Language::TXL => "txl",
            Language::TypeLanguage => "type-language",
            Language::TypeScript => "typescript",
            Language::TypeSpec => "typespec",
            Language::Typst => "typst",
            Language::UnifiedParallelC => "unified-parallel-c",
            Language::Unity3DAsset => "unity3d-asset",
            Language::UnixAssembly => "unix-assembly",
            Language::Uno => "uno",
            Language::UnrealScript => "unrealscript",
            Language::UrWeb => "urweb",
            Language::V => "v",
            Language::Vala => "vala",
            Language::ValveDataFormat => "valve-data-format",
            Language::VBA => "vba",
            Language::VBScript => "vbscript",
            Language::vCard => "vcard",
            Language::VCL => "vcl",
            Language::VelocityTemplateLanguage => "velocity-template-language",
            Language::Verilog => "verilog",
            Language::VHDL => "vhdl",
            Language::VimHelpFile => "vim-help-file",
            Language::VimScript => "vim-script",
            Language::VimSnippet => "vim-snippet",
            Language::VisualBasicNET => "visual-basic-.net",
            Language::VisualBasic6_0 => "visual-basic-6.0",
            Language::Volt => "volt",
            Language::Vue => "vue",
            Language::Vyper => "vyper",
            Language::WavefrontMaterial => "wavefront-material",
            Language::WavefrontObject => "wavefront-object",
            Language::WDL => "wdl",
            Language::WebOntologyLanguage => "web-ontology-language",
            Language::WebAssembly => "webassembly",
            Language::WebAssemblyInterfaceType => "webassembly-interface-type",
            Language::WebIDL => "webidl",
            Language::WebVTT => "webvtt",
            Language::WgetConfig => "wget-config",
            Language::WGSL => "wgsl",
            Language::Whiley => "whiley",
            Language::Wikitext => "wikitext",
            Language::Win32MessageFile => "win32-message-file",
            Language::WindowsRegistryEntries => "windows-registry-entries",
            Language::wisp => "wisp",
            Language::WitcherScript => "witcher-script",
            Language::Wollok => "wollok",
            Language::WorldofWarcraftAddonData => "world-of-warcraft-addon-data",
            Language::Wren => "wren",
            Language::XBitMap => "x-bitmap",
            Language::XFontDirectoryIndex => "x-font-directory-index",
            Language::XPixMap => "x-pixmap",
            Language::X10 => "x10",
            Language::xBase => "xbase",
            Language::XC => "xc",
            Language::XCompose => "xcompose",
            Language::Xmake => "xmake",
            Language::XML => "xml",
            Language::XMLPropertyList => "xml-property-list",
            Language::Xojo => "xojo",
            Language::Xonsh => "xonsh",
            Language::XPages => "xpages",
            Language::XProc => "xproc",
            Language::XQuery => "xquery",
            Language::XS => "xs",
            Language::XSLT => "xslt",
            Language::Xtend => "xtend",
            Language::Yacc => "yacc",
            Language::YAML => "yaml",
            Language::YANG => "yang",
            Language::YARA => "yara",
            Language::YASnippet => "yasnippet",
            Language::Yul => "yul",
            Language::ZAP => "zap",
            Language::Zeek => "zeek",
            Language::ZenScript => "zenscript",
            Language::Zephir => "zephir",
            Language::Zig => "zig",
            Language::ZIL => "zil",
            Language::Zimpl => "zimpl",
        }
    }
}
